# Generated by Django 5.2.14 on 2026-05-13 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_code_snippet_project_youtube_url_projectcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='code_snippet',
        ),
    ]
