# Generated by Django 5.2.14 on 2026-05-13 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journey',
            options={},
        ),
        migrations.RemoveField(
            model_name='journey',
            name='order',
        ),
        migrations.AlterField(
            model_name='journey',
            name='text',
            field=models.CharField(),
        ),
    ]
