# Generated by Django 5.2.14 on 2026-05-13 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_journey_options_remove_journey_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='text',
            field=models.TextField(),
        ),
    ]
