# Generated by Django 5.2.14 on 2026-05-13 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_blog_video_blog_youtube_url_blogcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='blog_videos/'),
        ),
    ]
