# Generated by Django 5.2.14 on 2026-05-14 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_alter_blog_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcode',
            old_name='project',
            new_name='blog',
        ),
    ]
