# Generated by Django 5.2.14 on 2026-05-16 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_rename_project_blogcode_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
