# Generated by Django 5.2.14 on 2026-05-13 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='demo_video',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='github_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_free',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='live_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tech_stack',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
